services:
  app:
    build: .
    container_name: proteomutics-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-include *
    ports:
      - "8000:8000"
    volumes:
      - .:/app